server:
  port: 8401
spring:
  application:
    name: cloud-alibaba-sentinel
  cloud:
    nacos:
      discovery:
        #注册中心地址
        server-addr: localhost:8848
    sentinel:
      transport:
        #sentinel dashboard地址
        dashboard: localhost:8080
        #默认8719，若被占用，会自动加1，直到找到未被占用的端口
        port: 8719

#图形化展现
management:
  endpoints:
    web:
      exposure:
        include: '*'