server:
  port: 9527

spring:
  application:
    #巨坑 该处名称不能用下划线，否则在远程调用服务时候找不到路径，报错如下 Request URI does not contain a valid hostname
    name: cloud-gateway-service
  cloud:
    gateway:
      #开启通过服务名在注册中心上进行查找服务，进而可以进行负载
      discovery:
        locator:
          enabled: true
      routes:
        #路由id，要求唯一
        - id: payment_routh1
          #匹配后提供服务的路由地址
          uri: http://localhost:8001
          #断言路径匹配的进行路由
          predicates:
            - Path=/payment/getPaymentById/**
          #通过服务名来进行路由访问（服务提供方）
        - id: payment_routh2
          uri: lb://CLOUD-PAYMENT-SERVICE
          predicates:
            - Path=/payment/discovery
          #通过调用服务调用方而进行调用服务提供方服务范例（order->payment里面的方法）
        - id: payment_routh3
          uri: lb://CLOUD-ORDER-SERVICE
          predicates:
            - Path=/consumer/payment/getPaymentById/**



eureka:
  client:
    #表示将自己注册到注册中心
    register-with-eureka: true
    #是否从eureka server抓取已有的注册信息，默认为true，单节点无所谓，集群必须为true，配合ribbon进行负载均衡
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:7001/eureka,http://localhost:7002/eureka