server:
  port: 80

spring:
  application:
    name: feign-hystrix-order-service
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://139.224.228.145:3307/cloud2021?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456
  main:
    allow-bean-definition-overriding: true

eureka:
  client:
    #表示将自己注册到注册中心
    register-with-eureka: true
    #是否从eureka server抓取已有的注册信息，默认为true，单节点无所谓，集群必须为true，配合ribbon进行负载均衡
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:7001/eureka,http://localhost:7002/eureka
#设置feign客户端超时时间(openfeign默认支持ribbon)默认1秒
ribbon:
  #指的是简历连接所需要的时间，适用于网络情况正常的情况下，两端连接所需要的时间
  ReadTimeout: 5000
  #指的是建立连接后从服务器读取到可用资源所用的时间
  ConnectTimeout: 5000

#当开启hystrix之后，经过验证上述的ribbon无论调的时间再久也不会进行等待结果，直接就是返回超时报错，所以两者排斥，
#若是想要让ribbon有效，设置等待时间大于服务提供者消耗时间，那么关闭hystrix之后即可，否则不等到ribbon设置的等待时间
#立马返回超时报错
feign:
  hystrix:
    enabled: true

#设置hystrix的全局等待时间，默认1秒（如果服务提供方挂掉了，
#那么服务调用方是不需要等待自己设置的时间来等待，而是直接根据feign接口设置的fallback直接返回处理响应
#设置该时间主要是当双方服务都正常的情况下，那么服务调用方会等待服务提供方最多多长时间）
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 9000
